CREATE TYPE "IndustryType" AS ENUM (
  'RESTAURANT',
  'BAR',
  'SUPERMARKET',
  'HARDWARE_STORE',
  'WINE_SHOP',
  'CLOTHING_AND_FASHION_SHOP',
  'BOOKSHOP',
  'COSMETIC_AND_SKINCARE_SHOP',
  'CONSTRUCTION_SHOP',
  'OTHER'
);

ALTER TABLE "tenants"
ALTER COLUMN "industry" DROP DEFAULT;

ALTER TABLE "subscription_prices"
ALTER COLUMN "industry" DROP DEFAULT;

ALTER TABLE "tenants"
ALTER COLUMN "industry" TYPE "IndustryType"
USING (
  CASE UPPER(REPLACE("industry", ' ', '_'))
    WHEN 'RESTAURANT' THEN 'RESTAURANT'::"IndustryType"
    WHEN 'RESTAURANTS' THEN 'RESTAURANT'::"IndustryType"
    WHEN 'BAR' THEN 'BAR'::"IndustryType"
    WHEN 'BARS' THEN 'BAR'::"IndustryType"
    WHEN 'SUPERMARKET' THEN 'SUPERMARKET'::"IndustryType"
    WHEN 'HARDWARE' THEN 'HARDWARE_STORE'::"IndustryType"
    WHEN 'HARDWARE_STORE' THEN 'HARDWARE_STORE'::"IndustryType"
    WHEN 'HARDWARE_STORES' THEN 'HARDWARE_STORE'::"IndustryType"
    WHEN 'WINE_SHOP' THEN 'WINE_SHOP'::"IndustryType"
    WHEN 'WINE_SHOPS' THEN 'WINE_SHOP'::"IndustryType"
    WHEN 'CLOTHING_&_FASHION_SHOPS' THEN 'CLOTHING_AND_FASHION_SHOP'::"IndustryType"
    WHEN 'CLOTHING_AND_FASHION_SHOP' THEN 'CLOTHING_AND_FASHION_SHOP'::"IndustryType"
    WHEN 'CLOTHING_AND_FASHION_SHOPS' THEN 'CLOTHING_AND_FASHION_SHOP'::"IndustryType"
    WHEN 'BOOKSHOP' THEN 'BOOKSHOP'::"IndustryType"
    WHEN 'BOOKSHOPS' THEN 'BOOKSHOP'::"IndustryType"
    WHEN 'COSMETIC_&_SKINCARE_SHOPS' THEN 'COSMETIC_AND_SKINCARE_SHOP'::"IndustryType"
    WHEN 'COSMETIC_AND_SKINCARE_SHOP' THEN 'COSMETIC_AND_SKINCARE_SHOP'::"IndustryType"
    WHEN 'COSMETIC_AND_SKINCARE_SHOPS' THEN 'COSMETIC_AND_SKINCARE_SHOP'::"IndustryType"
    WHEN 'CONSTRUCTION_SHOP' THEN 'CONSTRUCTION_SHOP'::"IndustryType"
    WHEN 'CONSTRUCTION_SHOPS' THEN 'CONSTRUCTION_SHOP'::"IndustryType"
    WHEN 'BUSINESS' THEN 'OTHER'::"IndustryType"
    WHEN 'OTHER' THEN 'OTHER'::"IndustryType"
    ELSE 'OTHER'::"IndustryType"
  END
);

ALTER TABLE "subscription_prices"
ALTER COLUMN "industry" TYPE "IndustryType"
USING (
  CASE UPPER(REPLACE("industry", ' ', '_'))
    WHEN 'RESTAURANT' THEN 'RESTAURANT'::"IndustryType"
    WHEN 'RESTAURANTS' THEN 'RESTAURANT'::"IndustryType"
    WHEN 'BAR' THEN 'BAR'::"IndustryType"
    WHEN 'BARS' THEN 'BAR'::"IndustryType"
    WHEN 'SUPERMARKET' THEN 'SUPERMARKET'::"IndustryType"
    WHEN 'HARDWARE' THEN 'HARDWARE_STORE'::"IndustryType"
    WHEN 'HARDWARE_STORE' THEN 'HARDWARE_STORE'::"IndustryType"
    WHEN 'HARDWARE_STORES' THEN 'HARDWARE_STORE'::"IndustryType"
    WHEN 'WINE_SHOP' THEN 'WINE_SHOP'::"IndustryType"
    WHEN 'WINE_SHOPS' THEN 'WINE_SHOP'::"IndustryType"
    WHEN 'CLOTHING_&_FASHION_SHOPS' THEN 'CLOTHING_AND_FASHION_SHOP'::"IndustryType"
    WHEN 'CLOTHING_AND_FASHION_SHOP' THEN 'CLOTHING_AND_FASHION_SHOP'::"IndustryType"
    WHEN 'CLOTHING_AND_FASHION_SHOPS' THEN 'CLOTHING_AND_FASHION_SHOP'::"IndustryType"
    WHEN 'BOOKSHOP' THEN 'BOOKSHOP'::"IndustryType"
    WHEN 'BOOKSHOPS' THEN 'BOOKSHOP'::"IndustryType"
    WHEN 'COSMETIC_&_SKINCARE_SHOPS' THEN 'COSMETIC_AND_SKINCARE_SHOP'::"IndustryType"
    WHEN 'COSMETIC_AND_SKINCARE_SHOP' THEN 'COSMETIC_AND_SKINCARE_SHOP'::"IndustryType"
    WHEN 'COSMETIC_AND_SKINCARE_SHOPS' THEN 'COSMETIC_AND_SKINCARE_SHOP'::"IndustryType"
    WHEN 'CONSTRUCTION_SHOP' THEN 'CONSTRUCTION_SHOP'::"IndustryType"
    WHEN 'CONSTRUCTION_SHOPS' THEN 'CONSTRUCTION_SHOP'::"IndustryType"
    WHEN 'BUSINESS' THEN 'OTHER'::"IndustryType"
    WHEN 'OTHER' THEN 'OTHER'::"IndustryType"
    ELSE 'OTHER'::"IndustryType"
  END
);

ALTER TABLE "tenants"
ALTER COLUMN "industry" SET DEFAULT 'OTHER';

ALTER TABLE "subscription_prices"
ALTER COLUMN "industry" SET DEFAULT 'OTHER';
